name: MyWorkflow file 
on: 
  push:
    branches: [main]

jobs:
  builds:
    runs-on: Ubuntu- 16.04
    name: My Build
    steps: 
      - name: Check out code
        uses: actions/checkout@v3
      - name: Printing a greeting 
        run:
          echo "Hello world" 
