name: MyWorkflow file 
on: 
  push:
    branches: [main]

jobs:
  builds:
    # create VM with ubuntu OS
    runs-on: Ubuntu- 20.04
    name: My Build
    steps: 
    # first step to say hello
      - name: Check out code
        uses: actions/checkout@v3
      - name: Printing a greeting 
        run: |
          echo "Hello world"
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12' #set up python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
