name: My Second Workflow file 
on: 
  pull_request: 
    branches: [main]

jobs:
  build2:
    # create VM with ubuntu OS
    runs-on: Ubuntu-20.04
    # name: My Build
    steps: 
    # first step to say hello
      - name: Greeting steps 
        run: |
          echo "Hello world"
    # this is where i checkout my codes       
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Print content of repo
        run: |
          ls
    # Install python
      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
         python-version: '3.10' #set up python version
         
      - name: Check version of python
        run: | 
         python --version
         
    # Install dependencies if any
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
         pip install pytest pytest-cov
      # begin test   
      - name: Begin pytest
        run: |
          pytest -v -cov --junitxml=report.xml

      # this is where we access the hidden repo
      - name: Checkout Hidden repo
        uses: actions/checkout@v4
        with:
          repository: gracierchua7/UOBHidden
          path: hiddenfolder
          token: ${{ secrets.SECRETUOB }}

      # this prints out the hidden files
      - name: Print out hidden files 
        run: |
          ls
          cd hiddenfolder
          ls
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            *.xml
